### ISSUE TITLE
madcore.schedule.set fixes

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/core#4]
1) madcore.schedule.set job is triggered by outside process. it is not to run hourly.
2) job parameters has been changed without team agreement. this job is being triggered from app, it had parameters separated for a reason, please revert back to agreed parameters.

**Comment by botzill** [comment]
About the cron , probably left from previouse template, was not added by me. About the input parameter I remember that we agree on it to be JSON format. So, can't we change the interface to JSON ?

**Comment by styk-tv** [comment]
@botzill jobs are ment to be run as stand alone, please update job and script arguments to support run with separate parameters, only exception is the instance list which is comma delimited. i'm ok with those being separate in jenkins, merged in bash and passed onto python as one

**Comment by botzill** [comment]
OK, fixed https://github.com/madcore-ai/core/pull/5

**Comment by styk-tv** [comment]
Merged
